# gitlab-integration-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-gitlab-secret
  namespace: demo-project
type: Opaque
stringData:
  GITLAB_TOKEN: glpat-1edPtu4sVjWAbdVm61PCVW86MQp1OmE1CA.01.0y0gnpfpe
